

# The id
id="mygroovyenginecontentpack" #mandatory

# The version number
version="1.0.0" #mandatory

# A display name for the mod
displayName="My Groovy Engine Content pack" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name containing a logo for display
#logoFile="examplemod.png" #optional

# A text field displayed in the UI
#credits="" #optional

# A text field displayed in the UI
authors="YourName" #optional

# The description text for the content pack
description='''This is a content pack''' #mandatory